### ISSUE TITLE
Snap build issues

### ISSUE THREAD

**Issue by KeitIG** [KeitIG/museeks#383]
On my Ubuntu VM, `npm run package:l` results in:

```
Error: spawn snapcraft ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at spawn (/home/pierre/Documents/museeks/node_modules/builder-util/src/util.ts:200:3)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/targets/snap.ts:116:13
    at Generator.next (<anonymous>)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at SnapTarget.build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/targets/snap.js:139:11)
    at taskManager.addTask.default.map.it (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:122:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:122:23)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:117:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/platformPackager.js:201:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:361:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/pierre/Documents/museeks/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:423:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:305:52
    at Generator.next (<anonymous>)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:367:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:267:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:323:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/pierre/Documents/museeks/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/pierre/Documents/museeks/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:49:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:49:33)
    at Object.runCommand (/home/pierre/Documents/museeks/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/pierre/Documents/museeks/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/pierre/Documents/museeks/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by YurySolovyov** [comment]
quick guess: no snap development tooling installed?

**Comment by KeitIG** [comment]
Not bad, after installing `snapcraft`, I am still getting this

```
Issues while validating snapcraft.yaml: The 'apps/museeks/plugs' property does not match the required schema: ['desktop', 'desktop-legacy', 'home', 'x11', 'unity7', 'browser-support', 'network', 'gsettings', 'pulseaudio', 'opengl', 'desktop-legacy', 'desktop'] has non-unique elements
```

it looks like snapcraft.yml is wrongly generated

**Comment by YurySolovyov** [comment]
what happens if you drop [this field](https://github.com/KeitIG/museeks/blob/master/package.json#L72) ?

**Comment by KeitIG** [comment]
After some experimentations, the traceback is pretty clear:

```
pierre@ubuntu-virtualbox:~/Documents/museeks$ npm run package:l

> museeks@0.8.1 package:l /home/pierre/Documents/museeks
> build -l --ia32

  • electron-builder version=19.55.3
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/electron-builder.yaml
  • no native production dependencies
  • packaging       platform=linux arch=ia32 electron=1.7.9 appOutDir=dist/linux-ia32-unpacked
  • building        target=AppImage arch=ia32 file=dist/museeks-0.8.1-i386.AppImage
  • building        target=snap arch=ia32 file=dist/museeks_0.8.1_i386.snap
Setting target machine to 'i386'
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.34+17.10', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/__main__.py", line 19, in <module>
    run(prog_name='snapcraft')
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 109, in prime
    _execute('prime', parts, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/lifecycle.py", line 31, in _execute
    lifecycle.execute(command, project_options, parts)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/lifecycle.py", line 113, in execute
    config = snapcraft.internal.load_config(project_options)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/__init__.py", line 24, in load_config
    return Config(project_options)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_config.py", line 124, in __init__
    snapcraft_yaml=self.snapcraft_yaml_path)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_parts_config.py", line 55, in __init__
    self._process_parts()
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_parts_config.py", line 85, in _process_parts
    self.load_part(part_name, plugin_name, properties)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/project_loader/_parts_config.py", line 169, in load_part
    definitions_schema=self._validator.definitions_schema)
  File "/usr/lib/python3/dist-packages/snapcraft/internal/pluginhandler/_plugin_loader.py", line 78, in load_plugin
    plugin.enable_cross_compilation()
  File "/usr/lib/python3/dist-packages/snapcraft/_baseplugin.py", line 182, in enable_cross_compilation
    'to a different target architecture'.format(self.name))
NotImplementedError: The plugin used by 'desktop-gtk2' does not support cross-compiling to a different target architecture
Error: snapcraft exited with code 1
    at ChildProcess.childProcess.once.code (/home/pierre/Documents/museeks/node_modules/builder-util/src/util.ts:241:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (/home/pierre/Documents/museeks/node_modules/builder-util/src/util.ts:200:3)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/targets/snap.ts:116:13
    at Generator.next (<anonymous>)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at SnapTarget.build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/targets/snap.js:139:11)
    at taskManager.addTask.default.map.it (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:120:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:120:23)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/platformPackager.ts:115:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/platformPackager.js:202:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:364:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/pierre/Documents/museeks/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:432:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:308:52
    at Generator.next (<anonymous>)
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/pierre/Documents/museeks/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:376:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder-lib/src/packager.ts:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/pierre/Documents/museeks/node_modules/electron-builder-lib/out/packager.js:332:11)
    at /home/pierre/Documents/museeks/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/pierre/Documents/museeks/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/pierre/Documents/museeks/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/home/pierre/Documents/museeks/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/pierre/Documents/museeks/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/pierre/Documents/museeks/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/pierre/Documents/museeks/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  • building embedded block map file=dist/museeks-0.8.1-i386.AppImage
pierre@ubuntu-virtualbox:~/Documents/museeks$ 

```

I think building ia32 snaps from x64 is a nope.

**Comment by YurySolovyov** [comment]
We can still release x64 and other packaging formats, right?

**Comment by KeitIG** [comment]
I'm trying to find a way to build x64 only for deb and AppImage at the moment + trying to see if I can build snaps for 32 bits anyway

**Comment by KeitIG** [comment]
Looks a bit like https://github.com/electron-userland/electron-builder/issues/1272

**Comment by YurySolovyov** [comment]
[some new snap docs](https://github.com/electron/electron/blob/a033a9cd5db2937a9ed743cb90085018d2a4c63c/docs/tutorial/snapcraft.md)
